config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: {omniauth_callbacks:"users/omniauth_callbacks"}
  root 'search#index'

  resources :charges

  resources :trending, only: :index
  
  get '/', to:'search#index' 
  post '/', to: 'search#create', as: 'submit_search'

  get '/songs', to: 'songs#index'
  post '/songs', to: 'songs#create', as: 'add_to_my_songs'
  patch '/songs/:id', to: 'songs#update', as: 'rate_songs'

  delete '/songs/:id', to: 'songs#destroy', as:'delete_songs'

  post '/rate' => 'rater#create', :as => 'rate'

  

end

app/models/rdio.rb
module Rdio
  
  # def self.client
  #   @client ||= RdioApi.new(consumer_key: Rails.application.secrets.rdio_key,
  #                           consumer_secret: Rails.application.secrets.rdio_secret) 
  # end

     def self.client
     @client ||= RdioApi.new(consumer_key: "49hav4bae3jttacpk3vmtu42",
                             consumer_secret: "yx5VGpBx4B") 
    end

  def self.search(text)
    response = Rdio.client.search(query: text, types: 'song')
    response.results.map { |result| Song.new(result) }
  end

  class Song
    attr_reader :name, :artist, :artwork, :songalbum, :artistid, :albumid, :songid
    def initialize(result)
      @name =   result.name
      @artist = result.artist
      @artwork = result.icon400
      ######other attrs
      @songalbum = result.album
      ### stat attr
      @artistid = result.artistKey
      @albumid = result.albumKey
      @songid = result.to_hash['key']
    end
  end
end

 # Rdio::Song

# def uid
#   @uid
# end

#this is a class (song) within a class (Rdio), so the object thats created from this
# is a Rdio::Song
#check in rails c . 

#anytime we say Rdio.client (client is a method that weve defined)
#same for Rdio.search ( "randomshithere")
#it will take "randomshithere" to search database
#then it will take the results it gets from there and turn them all to 
#song objects, song(resultfromapi)
#it gives song three attributes 
#Song.name which is  -  resultfromapi.name
#Song.artist which is   resultfromapi.artist
#Song.artwork which is  resultfromapi.icond400 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :songs, dependent: :destroy

  serialize :twitter_omniauth_data
  serialize :facebook_omniauth_data


  # def add_hello_to_user(user)
  #   user.name="hello"
  #   user.email=user.email
  #   user.password=user.password
  #   user.save
  # end

  def omniauth_data
    if omniauth_raw_data?
     # Assumes that omniauth_raw_data is safe to eval!
     JSON.parse(omniauth_raw_data)
    else
      {}
    end 
  end

  def authenticated_by_facebook?
    omniauth_data['provider'] == 'facebook'
  end

  def authenticated_by_twitter?
    omniauth_data['provider'] == 'twitter'
  end

  def profile_image_url
    data = omniauth_data
    if authenticated_by_facebook?
      data['info']['image']
    elsif authenticated_by_twitter?
      data['profile_image_url']
    else
      nil
    end
  end

  def email_required?
    false
  end

  def password_required?
    provider.nil?
  end

  def self.find_or_create_from_twitter(twitter_omniauth_data)
    user = User.where(provider: :twitter, uid: twitter_omniauth_data["uid"]).first
    unless user
      # twitter_handle = twitter_omniauth_data['info']['nickname'],
      user = User.create(provider: :twitter, uid: twitter_omniauth_data["uid"],
      name: "@#{twitter_omniauth_data['info']['nickname']}",
        # image: twitter_omniauth_data["info"]["image"],
      twitter_credentials_token:  twitter_omniauth_data["credentials"]["token"],
      twitter_credentials_secret: twitter_omniauth_data["credentials"]["secret"],
      omniauth_raw_data: twitter_omniauth_data["extra"]["raw_info"].merge(provider: "twitter").to_json)
    end
    user
  end

  def self.find_or_create_from_facebook(facebook_omniauth_data)
    user=User.where(provider: :facebook, uid:facebook_omniauth_data["uid"]).first
    unless user
      user=User.create(provider: :facebook, 
                      uid: facebook_omniauth_data["uid"],
                      email: facebook_omniauth_data["info"]["email"],
                      name: facebook_omniauth_data["info"]["name"],
                      facebook_credentials_token: facebook_omniauth_data["credentials"]["token"],
                      facebook_credentials_expires_at: facebook_omniauth_data["credentials"]["expires_at"],
                      omniauth_raw_data: facebook_omniauth_data.to_json)
     end
    user
  end

  ratyrate_rater

  def rating_for_song(song)
    rating_for_song = ratings_given.where(rateable_type: 'Song', rateable_id: song.id).first

    if rating_for_song.present?
      rating_for_song.stars
    else
      0.0
    end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = params[:customamount]
    @convertedamount = @amount.to_i
    @dollaramount = @convertedamount*100
    customer = Stripe::Customer.create(
      :email => 'customer@mmdb.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @dollaramount,
      :description => 'mmdb customer',
      :currency    => 'cad'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    before_action :authenticate_user!, only: [:create, :index]

    def index #will show all the added songs
      if user_signed_in? == true
        @songs=current_user.songs.order(rating: :desc)          
        @songs = @songs.search(params[:searchmydb])  if params[:searchmydb].present?
        render params[:listing] ? "listing" : "index"
      else
        redirect_to root_path
      end
    end


    def create # will add new songs to my database
      @songs=Song.all
      if @songs.exists?(name: params[:name],
          artist: params[:artist],
          artwork: params[:artwork],
          user_id: current_user.id)
          #current_user.has_song_with_uid?(params[:uid])
          redirect_to search_path, notice: "Song already exists"
      else
        @song=Song.new(name:     params[:name],
          artist:   params[:artist],
          artwork:  params[:artwork],
          songalbum: params[:songalbum],
          artistid: params[:artistid],
          albumid: params[:albumid],
          songid: params[:songid]
          )

          @song.user=current_user

          if @song.save
            redirect_to add_to_my_songs_path, notice: "song added"
          else 
            redirect_to search_path, notice: "something went wrong"
          end
      end
    end

  def update
    @song=Song.find(params[:id])
    @song.rating = params[:song][:rating].to_i

    if @song.save
      redirect_to songs_path, notice: "rating saved!"
    else
      redirect_to songs_path, notice: "song could not be saved!"
    end
  end

  def destroy
    @song=Song.find(params[:id])
    if @song.delete
      redirect_to songs_path, notice: "Song removed!"
    else
      redirect_to songs_path, notice: "song could not be removed!"
    end
  end
end

app/controllers/trending_controller.rb
class TrendingController < ApplicationController

  def index

    @songs = Song.all
  
  end


 


end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/trending_helper.rb
module TrendingHelper
end

app/views/charges/create.html.erb
<div class="container" id="paymentpage">

<h2>Thank you for you donation of  <strong>
</strong>!</h2>


</div>

app/views/charges/new.html.erb
<div class="container center" id="paymentpage">
    <%= form_tag charges_path do %>
      <label class="amount">
      <!-- <span>Amount: $2.00</span><br> -->
      <input name="customamount" placeholder="Enter amount"></input>
      </label>
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= ENV["STRIPE_PUBLIC_KEY"] %>"
        data-description="Donate"
        data-amount="customamount">
      </script>
   <%end%>
</div>

<div id="brand">
SlideIn/Out
</div>
<input type ="checkbox" id="menuToggle">
<label for="menuToggle" id="menu-icon">&#9776;</label>

<nav id="slideinmenu">
  <li><a href="#">Home</a></li>
  <li><a href="#">check</a></li>
  <li><a href="#">test</a></li>
  <li><a href="#">playwithme</a></li>
  <li><a href="#">Hpome</a></li>
</nav>

<!-- 
<div id="paymentpagecompanies">
fdsafsaf
ds
fads
f
</div> -->


<div id="donationthumbnail">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mmdb</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>


<!-- Google font-->
<link href='http://fonts.googleapis.com/css?family=Lato:400,900' rel='stylesheet' type='text/css'>

<!--Font Awesome (icons) -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

<!-- <nav class="navbar navbar-inverse"> -->
<nav class="navbar-default">
<!-- <%#=image_tag 'mmdb.png', id: "mylogo"%>&nbsp;&nbsp;&nbsp; -->
  <span id="navbarname">mymusicdatabase.</span>

  <span id="userauth">
  <% if user_signed_in? %>
      Hi <%=current_user.name%>
        <%if current_user.profile_image_url.present? %>
          <%= image_tag current_user.profile_image_url %>
        <%end%>
          <%#=link_to "My database", "/songs"%>
          <%=link_to 'Logout',destroy_user_session_path,:method =>:delete %>
        <%else%> 
          
          <span class="loginstuff">
            <i class="fa fa-user fa-2x"></i>

      <%=link_to 'LOGIN',new_user_session_path%>
    <%=link_to image_tag('twitterbtn.jpg', :id => 'twitterbtn'), user_omniauth_authorize_path(provider: :twitter)%>
    <%=link_to image_tag('fbbtn.jpg', :id => 'facebookbtn'), user_omniauth_authorize_path(provider: :facebook)%>


          </span>

          
    <%end%>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%=  alert %></p>
  </nav>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/create.html.erb
<!-- API SEARCH RESULTS PAGE (DISPLAY RESULTS AS RDIO::SONG OBJECTS) -->
<!-- TODO: CSS FLIP EFFECT  -->
<!-- background image -->
<style>
  body { background-color:#162955;
  }
</style>
<%#=render plain: params[:usersearch]%>
<span id="sidebar">
  <%=link_to "Go back home", root_path%><br>
  <%=link_to "search again", root_path%><br><br><br><br><br>
  <%=link_to "my collection", songs_path%><br><br>
  <%=link_to "top songs", ""%><br>
  <%=link_to "top artists", ""%><br>
  <%=link_to "top albums", ""%><br>
</span>




<!-- all api results(rdio::song objects) -->

<div class="container">
  <div class="row">
  <h1 id="results_title">Results</h1><hr>

    <%if @result.present? %>
      <%@result.each do |x|%>
        <div class="col-md-4">
          <div><%=image_tag x.artwork %></div><br>
          <div id="songname"><%=x.name%></div>
          <div id="songartist"><%=x.artist%></div>
          <div id="otherinfo">Other info:</div>
          <div id="songalbum">albumname:<%=x.songalbum%></div>
          <div id="songid">Songid:<%=x.songid%></div>
          <div id="artistid">artistid:<%=x.artistid%></div>
          <div id="albumid">albumid:<%=x.albumid%></div>
          <%=link_to "Add this Song to my Collection", 
          songs_path(:name => x.name, :artist => x.artist, 
          :artwork => x.artwork, :songalbum => x.songalbum,
          :songid => x.songid, :artistid => x.artistid,
          :albumid => x.albumid), method: :post%>
        </div>
    <%end%>
    <%else%>
      <%="Sorry, no results matched that search"%>
    <%end%>
  </div>
</div>

app/views/search/index.html.erb
<div id="mainpagetho">
  <%= form_tag url: submit_search_path, method: :post do %>
        <input type="text" name="usersearch" class="form-control" placeholder="song search.." 
         required/>
    <%end%>
</div>
    
<div id="mainpage2">
  <i class="fa fa-refresh fa-spin fa-5x"></i>  
  <i class="fa fa-flag fa-5x"></i>
  <i class="fa fa-music fa-5x"></i>
    <div class="container">
      <h5 id="heading2">.My music database allows you to search through millions of songsand upload them to ur very own music library.
      <br> Get started now!
      </h5>
    </div>
</div>

<div id="mainpage3">
  <div class="container"> 
    <i class= "fa fa-quote-left fa-3x pull-left fa-border"></i>
    <h5 id="heading3"> store all your music preferences in one place.
    </h5>
  </div>
</div>
<%= link_to "Donate", new_charge_path %>
<%= link_to "Whats Trending?", trending_index_path%>

app/views/songs/index.html.erb
<style>
body{
background-color:#162955;
}
</style>

<%=link_to "search for more", search_path %> || 
<%=link_to "home page", root_path%> 

<hr>



<!--########          MY COLLECTION INDEX VIEW       #####-->

<div class="inlinedivs" id="usercollection">
<h2> <%=current_user.name%>'s Collection </h2>
</div>
<div class="inlinedivs">
  <%=form_tag("/songs", method: "get") do %>
  <%#=label_tag(:searchmydb, "Search my collection:") %>
  <%=text_field_tag(:searchmydb)%>
  <%=submit_tag("Search my collection") %>
  <%end%>
</div>
<div class="inlinedivs">
  <%#= button_to "list view", action: "index" %>
  <!-- <form method="get" action="/controller/index2.html.erb" class="button_to"></form> -->
  <%= link_to "View as List", songs_path(listing: true) %>
  <%#=link_to "list view", "/songs"%>
  <%#=render :partial => "index2" %>
</div>
<hr>
<!-- #########################my collection display(thumbnails)########################## -->
<%@songs.each do |mysong| %>
  <div class="col-md-4">
    <div><%=image_tag mysong.artwork %></div><br>
    <div id="songname">SONGNAME:<%=mysong.name%></div>
    <div id="songartist">SONGARTIST:<%=mysong.artist%></div>
    <div id="songalbum">SONGALBUM:<%=mysong.songalbum%></div>
    <div id= "artistid">ARTISTID:<%=mysong.artistid%></div>
    <div id="albumid">ALBUMID:<%=mysong.albumid%></div>
    <div id="songid">SONGID:<%=mysong.songid%></div>
    <div id="songrating">My Rating:<%= rating_for mysong, "rating", :enable_half => true, :disable_after_rate => false %></div>


    <%#=form_for :song, url: rate_songs_path(mysong), method: :patch do |f| %>
    <%#= f.number_field :rating, min:0, max:5 %>
    <%#= f.submit "submit" %>
    <%#end%> 

    <!-- MY RATING:<%#=mysong.rating%><br> -->
    <%=link_to "Remove from my collection", delete_songs_path(mysong), 
    method: :delete, data:{confirm: "are you sure?"} %>
  </div>
<%end%>

app/views/songs/listing.html.erb
Listing
<%=link_to "search for more", search_path %>
<hr>

<style>
body{
  background-color: gray;
}
</style>


<!--###########my collection search / list view / other actions################# -->

<div class="inlinedivs" id="usercollection">
<h2> <%=current_user.name%>'s Collection </h2>
</div>
<div class="inlinedivs">
  <%=form_tag("/songs", method: "get") do %>
  <%#=label_tag(:searchmydb, "Search my collection:") %>
  <%=text_field_tag(:searchmydb)%>
  <%=submit_tag("Search my collection") %>
  <%end%>
</div>
<div class="inlinedivs">
  <%#= button_to "list view", action: "index" %>
  <!-- <form method="get" action="/controller/index2.html.erb" class="button_to"></form> -->
  <%=link_to "view as thumbnails", songs_path%>
  <%#=render :partial => "index2" %>
</div>
<hr>
<!-- #########################my collection display (list view)########################## -->
<div class="container">

<table class="table">
  <tr>
        <th></th>
        <th>Name</th>
        <th>Artist</th>
        <th>Album</th>
        <th>Artistid</th>
        <th>Albumid</th>
        <th>Songid</th>
        <th>My Rating</th>
        <th colspan="4"></th>
     </tr>
     <hr>
 
<%@songs.each do |mysong| %>
<tr>
<td><div id="listimage"><%=image_tag mysong.artwork%></div></td>
<td><%=mysong.name%></td>
<td><%=mysong.artist%></td>
<td><%=mysong.songalbum%></td>
<td><%=mysong.artistid%></td>
<td><%=mysong.albumid%></td>
<td><%=mysong.songid%></td>
<td><%=rating_for mysong, "rating", :enable_half => true, :disable_after_rate => false%></td>
</tr> 


      <% end %>
      </table>
      <hr>
    </div>


 

app/views/trending/index.html.erb
<h1>#WhatsTrending?<h1><br><hr>

<!-- works -->
<%#@songs.each do |song| %>
  <%#=song.name%>
<%#end%>

<!-- works -->
<%#=@songs.group(:songid).count%>


<!-- works -->
<%#=all_counts = @songs.group(:songid).count%>
<%#=all_counts.max%>
<hr>

Trending Songs
<hr>

<%all_counts = @songs.group(:songid).count%>
<!-- <br><br> "the highest value is:" -->
<%#=maxvalue = all_counts.max%>
<%all_counts.each do |x,y|%>
  <%if y == all_counts.values.max%>
  songid:<%=songkeys=x%>,
  song name:<%=songname=@songs.find_by(songid: songkeys).name%><br>
  <%=image_tag songartwork = @songs.find_by(songid: songkeys).artwork%>
  number of collections this song is included in: <%=y%><br><hr>
  <%end%>
  <%end%>
<hr><br><br><br><br>

<!-- Trending Albums -->
<%#all_album_counts = @songs.group(:albumid).count%>
<!-- <br><br> "the highest value is:" -->
<%#=maxvalue = all_counts.max%>
<%#all_album_counts.each do |x,y|%>
  <%#if y == all_album_counts.values.max%>
  <!-- albumid:<%#=albumkeys=x%>, -->
  <!-- album name:<%#=songname=@songs.find_by(albumid: albumkeys).name%><br> -->
  <%#=image_tag songartwork = @songs.find_by(albumid: albumkeys).artwork%>
  <!-- number of collections this song is included in: <%#=y%><br><hr> -->
  <%#end%>
  <%#end%>
<!-- <hr> -->

<!-- Trending Artists -->
<%#=song = @songs.find_by(name:'Random')%>
<%#=song.artist%>

<!-- user = User.find_by(name: 'David') -->


<!-- Hash[all_counts.select{ |k, v| v == max} ] -->

<%#=@songs.where(songid: :songid)%>

<%#=all_counts.each {|k,v| puts k if v == all_counts.values.max } %>


<!-- max = my_hash.values.max
Hash[my_hash.select { |k, v| v == max}] -->